# Generated by Django 3.0.4 on 2020-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kww_celery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personage',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
