# Generated by Django 3.0.4 on 2020-03-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='workers',
            new_name='participants',
        ),
    ]
