# Generated by Django 3.0.4 on 2020-03-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectparticipation',
            old_name='tecnologies',
            new_name='technologies',
        ),
    ]
