# Generated by Django 3.0.4 on 2020-07-04 15:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipationissue',
            name='issue',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technologyuse',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TechnologieIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kww_app.ProjectParticipationIssue')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kww_app.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='projectparticipationissue',
            name='technologies',
            field=models.ManyToManyField(through='kww_app.TechnologieIssue', to='kww_app.Technology'),
        ),
    ]
