# Generated by Django 3.0.4 on 2020-03-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0004_auto_20200314_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kww_app.Company'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='kww_app.Participant'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='kww_app.Role'),
        ),
    ]
