# Generated by Django 3.0.4 on 2020-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0005_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
