# Generated by Django 3.0.4 on 2020-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0006_projecttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
