# Generated by Django 3.0.4 on 2020-07-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0008_auto_20200712_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='countries',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kww_app.Country'),
        ),
    ]
