# Generated by Django 3.0.4 on 2020-07-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0010_auto_20200719_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
