# Generated by Django 3.0.4 on 2020-03-08 16:05
import os

from django.core import serializers
from django.db import migrations
from django.db.models import signals
import factory

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'initial.json'


@factory.django.mute_signals(signals.pre_save, signals.post_save)
def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)

    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0001_initial'),
    ]

    operations = [
        #migrations.RunPython(load_fixture),
    ]
