# Generated by Django 3.0.4 on 2020-03-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0002_auto_20200308_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='technologies',
            field=models.ManyToManyField(related_name='participants', through='kww_app.TechnologyUse', to='kww_app.Technology'),
        ),
        migrations.AddField(
            model_name='technologyuse',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kww_app.Participant'),
        ),
        migrations.AlterField(
            model_name='technologyuse',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kww_app.Technology'),
        ),
    ]
