# Generated by Django 3.0.4 on 2020-03-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0003_auto_20200308_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyuse',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kww_app.Project'),
        ),
    ]
