# Generated by Django 3.0.4 on 2020-03-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kww_app', '0004_auto_20200308_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kww_app.Technology'),
        ),
    ]
